iv tq01_r1
dv tq01_r2
dv tq01_r3
dv tq01_r4
dv tq01_r5l
dv tq01_r5c
iv tq01_r5r
iv tq01_r6

dv tq02_r1
dv tq02_r2
dv tq02_r3
dv tq02_r4
dv tq02_r5l
dv tq02_r5c
dv tq02_r5r
dv tq02_r6

dv tq03_r1
dv tq03_r2
dv tq03_r3
dv tq03_r4
dv tq03_r5l
dv tq03_r5c
dv tq03_r5r
dv tq03_r6

dv tq04_r1
dv tq04_r2
dv tq04_r3
dv tq04_r4
dv tq04_r5l
dv tq04_r5c
dv tq04_r5r
dv tq04_r6

dv tq05_r1
dv tq05_r2
dv tq05_r3
dv tq05_r4
dv tq05_r5l
dv tq05_r5c
dv tq05_r5r
dv tq05_r6

dv tq06_r1
dv tq06_r2
dv tq06_r3
dv tq06_r4
dv tq06_r5l
dv tq06_r5c
dv tq06_r5r
dv tq06_r6

dv tq07_r1
dv tq07_r2
dv tq07_r3
dv tq07_r4
dv tq07_r5l
dv tq07_r5c
dv tq07_r5r
dv tq07_r6

dv tq08_r1
dv tq08_r2
dv tq08_r3
dv tq08_r4
dv tq08_r5l
dv tq08_r5c
dv tq08_r5r
dv tq08_r6

dv tq09_r1
dv tq09_r2
dv tq09_r3
dv tq09_r4
dv tq09_r5l
dv tq09_r5c
dv tq09_r5r
dv tq09_r6

dv tq10_r1
dv tq10_r2
dv tq10_r3
dv tq10_r4
dv tq10_r5l
dv tq10_r5c
dv tq10_r5r
dv tq10_r6

dv tq11_r1
dv tq11_r2
dv tq11_r3
dv tq11_r4
dv tq11_r5l
dv tq11_r5c
dv tq11_r5r
dv tq11_r6

dv tq12_r1
dv tq12_r2
dv tq12_r3
dv tq12_r4
dv tq12_r5l
dv tq12_r5c
dv tq12_r5r
dv tq12_r6

dv tq13_r1
dv tq13_r2
dv tq13_r3
dv tq13_r4
dv tq13_r5l
dv tq13_r5c
dv tq13_r5r
dv tq13_r6

dv tq14_r1
dv tq14_r2
dv tq14_r3
dv tq14_r4
dv tq14_r5l
dv tq14_r5c
dv tq14_r5r
dv tq14_r6

dv tq15_r1
dv tq15_r2
dv tq15_r3
dv tq15_r4
dv tq15_r5l
dv tq15_r5c
dv tq15_r5r
dv tq15_r6

dv tq16_r1
dv tq16_r2
dv tq16_r3
dv tq16_r4
dv tq16_r5l
dv tq16_r5c
dv tq16_r5r
dv tq16_r6

dv tq17_r1
dv tq17_r2
dv tq17_r3
dv tq17_r4
dv tq17_r5l
dv tq17_r5c
dv tq17_r5r
dv tq17_r6

dv tq18_r1
dv tq18_r2
dv tq18_r3
dv tq18_r4
dv tq18_r5l
dv tq18_r5c
dv tq18_r5r
dv tq18_r6

dv tq19_r1
dv tq19_r2
dv tq19_r3
dv tq19_r4
dv tq19_r5l
dv tq19_r5c
dv tq19_r5r
dv tq19_r6

dv tq20_r1
dv tq20_r2
dv tq20_r3
dv tq20_r4
dv tq20_r5l
dv tq20_r5c
dv tq20_r5r
dv tq20_r6

dv tq21_r1
dv tq21_r2
dv tq21_r3
dv tq21_r4
dv tq21_r5l
dv tq21_r5c
dv tq21_r5r
dv tq21_r6

dv tq22_r1
dv tq22_r2
dv tq22_r3
dv tq22_r4
dv tq22_r5l
dv tq22_r5c
dv tq22_r5r
dv tq22_r6

dv tq23_r1
dv tq23_r2
dv tq23_r3
dv tq23_r4
dv tq23_r5l
dv tq23_r5c
dv tq23_r5r
dv tq23_r6

dv tq24_r1
dv tq24_r2
dv tq24_r3
dv tq24_r4
dv tq24_r5l
dv tq24_r5c
dv tq24_r5r
dv tq24_r6

dv tq25_r1
dv tq25_r2
dv tq25_r3
dv tq25_r4
dv tq25_r5l
dv tq25_r5c
dv tq25_r5r
dv tq25_r6

dv tq26_r1
dv tq26_r2
dv tq26_r3
dv tq26_r4
dv tq26_r5l
dv tq26_r5c
dv tq26_r5r
dv tq26_r6

dv tq27_r1
dv tq27_r2
dv tq27_r3
dv tq27_r4
dv tq27_r5l
dv tq27_r5c
dv tq27_r5r
dv tq27_r6

dv tq28_r1
dv tq28_r2
dv tq28_r3
dv tq28_r4
dv tq28_r5l
dv tq28_r5c
dv tq28_r5r
dv tq28_r6

# dv sm01
# dv sm02
# dv sm03
# dv sm04
# dv sm05
# dv sm06
# dv sm07
# dv sm08
# dv sm09
# dv sm10
# dv sm11
# dv sm12
# dv sm13
# dv sm14
# dv sm15
# dv sm16
# dv sm17
# dv sm18
# dv sm19
# dv sm20
# dv sm21
# dv sm22
# dv sm23
# dv sm24
# dv sm25
# dv sm26
# dv sm27
# dv sm28

# dv pd01
# dv pd02
# dv pd03
# dv pd04
# dv pd05
# dv pd06
# dv pd07
# dv pd08
# dv pd09
# dv pd10
# dv pd11
# dv pd12
# dv pd13
# dv pd14
# dv pd15
# dv pd16
# dv pd17
# dv pd18
# dv pd19
# dv pd20
# dv pd21
# dv pd22
# dv pd23
# dv pd24
# dv pd25
# dv pd26
# dv pd27
# dv pd28

# dv sa01
# dv sa02
# dv sa03
# dv sa04
# dv sa05
# dv sa06
# dv sa07
# dv sa08

# dv la01
# dv la02
# dv la03
# dv la04
# dv la05
# dv la06
# dv la07
# dv la08
# dv la09
# dv la10
# dv la11
# dv la12
# dv la13
# dv la14
# dv la15
# dv la16
# dv la17
# dv la18
# dv la19
# dv la20
# dv la21
# dv la22
# dv la23
# dv la24
# dv la25
# dv la26
# dv la27
# dv la28
# dv la29
# dv la30
# dv la31
# dv la32
# dv la33
# dv la34
# dv la35
# dv la36
# dv la37
# dv la38
# dv la39
# dv la40
# dv la41
# dv la42


#----- IVs -----
iv bpm_targetX
iv bpm_targetY
iv bpm_targetXSlope
iv bpm_targetYSlope
iv target_energy
